- name: Raspberry Pi Post Install
  hosts: all
  become: true
  vars:
    debug: true
  tasks:
    - name: Update and upgrade apt packages
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 86400

    - name: Install Docker
      ansible.builtin.apt:
        name: ["runc", "docker.io", "docker-compose"]
        allow_unauthenticated: true
        state: present
      become: true
      become_method: ansible.builtin.sudo

    - name: Create "docker" group
      ansible.builtin.group:
        name: "docker"
        state: present

    - name: Add "pi" user to "docker" group
      ansible.builtin.user:
        name: "pi"
        groups: "docker"
        append: true

    - name: Install docker-compose from official github repo
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    # https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module
    - name: Create portainer container
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce
        state: started
        recreate: true
        restart_policy: always
        published_ports:
          - "8000:8000"
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: Congratulations!
      ansible.builtin.debug:
        msg:
          - "Your Raspberry Pi is ready now!"
